### ISSUE TITLE
`LazyCell` should not be `const`

### ISSUE THREAD

**Issue by yutannihilation** [tomoyanonymous/mimium-rs#24]
While this isn't a problem at the moment, I see this clippy warning (if you are using VS Code, you can set `rust-analyzer.check.command` option to `clippy` to always see such warnings, but it might be a bit annoying):

```
warning: a `const` item should not be interior mutable
   --> mimium-lang\src\runtime\builtin_fn.rs:231:1
    |
231 | / pub const BUILTIN_FNS: LazyCell<[BuiltinFn; 49]> = LazyCell::new(|| {
232 | |     [
233 | |         i_i!(neg),
234 | |         i_i!(not),
...   |
306 | |     ]
307 | | });
    | |___^
    |
    = help: consider making this `Sync` so that it can go in a static item or using a `thread_local`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#declare_interior_mutable_const
    = note: `#[warn(clippy::declare_interior_mutable_const)]` on by default
```

[The explanation of `declare_interior_mutable_const`](https://rust-lang.github.io/rust-clippy/master/index.html#/declare_interior_mutable_const) says:

> Consts are copied everywhere they are referenced, i.e., every time you refer to the const a fresh instance of the `Cell` or `Mutex` or `AtomicXxxx` will be created, which defeats the whole purpose of using these types in the first place.

I think I've heard about this problem, but forgot how to deal with this (`static` `LazyLock`?). Let me file this here for now.

**Comment by tomoyanonymous** [comment]
The reason for using `LazyCell` for here is because `Type` contains recusive definition and requires heap allocation.
This global variable can simply be changed to a global function that generates the array.

**Comment by yutannihilation** [comment]
Thanks, then I'll address this in #25. I just remembered I need to modify `BUILTIN_FNS` as well...

**Comment by yutannihilation** [comment]
`BUILTIN_FNS` is now a global function. Closing this.

https://github.com/tomoyanonymous/mimium-rs/pull/25/commits/1075ba4d436171bef9386c5d4275ac9d89550c22
