### ISSUE TITLE
Refactor comment parser

### ISSUE THREAD

**Issue by tomoyanonymous** [tomoyanonymous/mimium-rs#33]
Currently, inline comment `//comment` inside function definition fails to parse.
The parser should be changed so that it can ignore comment token at anywhere in the process.
We can remove all the comment tokens before parsing but it maybe better to keep it as a metadata for the following expression id because it can be extended as an attribute or  documentation comment system.

**Comment by yutannihilation** [comment]
I expect there's a different syntax for metadata (e.g. `//` vs `///`), so I think it's fine to let the lexer to remove all the comments.

Also, if it's a metadata, it's parsed by the parser of the item that the metadata should belong to. For example, if a metadata is about a function, the metadata should be a field of `Function` (cf. [`syn::ItemFn`](https://docs.rs/syn/latest/syn/struct.ItemFn.html)). Accordingly, it's probably parsed by `func_parser()`, not by `comment_parser()`. So, probably we don't need to worry much about `comment_parser()`.

**Comment by tomoyanonymous** [comment]
ah, I haven't read rustc's AST representation. Then, indeed it seems okay to remove normal comments before parsing.

**Comment by yutannihilation** [comment]
More precisely, `///` is just syntax sugar for `#[doc]`, so it's treated as a usual `#[ ]`.

https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html
