### ISSUE TITLE
Pipe operator

### ISSUE THREAD

**Issue by yutannihilation** [tomoyanonymous/mimium-rs#56]
I [experimentally implemented a pipe operator,](https://github.com/tomoyanonymous/mimium-rs/compare/main...yutannihilation:mimium-rs:feat-pipe?expand=1) and got to know there are two types of pipes.

cf. https://github.com/tc39/proposal-pipeline-operator?tab=readme-ov-file#why-the-hack-pipe-operator

* explicit function call (Hack pipe): `value |> foo(%)`
* implicit function call (F# pipe): `value |> foo`

It seems my implementation is a simpler version of "Hack pipe," which is without the placeholder `%` by assuming the value is inserted into the first argument. Since my main language is R, I naturally assumed this is the pipe operator. On the other hand, Mimium's pipe is "F# pipe". I think this needs some discussion because both pipe have their pros and cons.

Is it common to use the F# style in this area? If I understand correctly, F#'s pipe is designed for combination with partial application. I'm wondering if there's any plan.

(I'm asking this simply because it looks easy to implement. Not sure about the importance of the feature itself)

**Comment by tomoyanonymous** [comment]
As far as I know, I do not know the language that has pipe operator for the musical languages. 
As you said, mimium' pipe operator is in between F# style and hack pipe but I am thinking to introduce syntax sugar to cover multiple arguments, as mimium does not have implicit partial application.

if we have the function like this

```rust
fn filter(input, freq, gain)->float{
 ...
}

fn dsp(input){
  input 
  |> filter(_, 440.0,-12.0)
}
```
If the single underscore(it's equivalent to `%` in the Hack pipe, but I derived this from SuperCollider) is supplied as an argument, it can be expanded to 

```rust
fn dsp(input){
  input 
  |> |x| filter(x, 440.0,-12.0)
}
```

Of course, this creates temporary closure but it can be easily optimized if the function inlining can be implemented.

In addition to this, it would be nice to allow that multiple argument as a single tuple (parameter pack) to combine with pipe operator.

```rust
fn dsp(input){
  (input,440.0,-12.0) 
  |> filter
}
```
