### ISSUE TITLE
CSV backend seems broken

### ISSUE THREAD

**Issue by yutannihilation** [tomoyanonymous/mimium-rs#86]
It seems it successfully finds the input device, but fails to pass it to `SystemPlugin`? In order to catch up with the recent updates, this might be a good practice for me (I'm yet to figure out how the plugins system works).

```
❯ cargo run --bin mimium-cli -- --output-format csv tmp.mmm

...

warning: `mimium-symphonia` (lib) generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/mimium-cli --output-format csv tmp.mmm`
[D] Filename: /home/yutani/repo/mimium-rs/tmp.mmm
[*] trying to connect default MIDI input device...
[*] Midi Input: Connected to Midi Through:Midi Through Port-0 14:0
ch0
thread 'main' panicked at mimium-midi/src/lib.rs:123:41:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`mimium-midi/src/lib.rs:123:41` is around here.

https://github.com/tomoyanonymous/mimium-rs/blob/00a43378674b567a486a6ca5cc941597d34c4b31/mimium-midi/src/lib.rs#L121-L124

**Comment by yutannihilation** [comment]
`after_main()` is called multiple times while `input` is `take()`n by the first call.

https://github.com/tomoyanonymous/mimium-rs/blob/00a43378674b567a486a6ca5cc941597d34c4b31/mimium-audiodriver/src/driver.rs#L104-L108

https://github.com/tomoyanonymous/mimium-rs/blob/00a43378674b567a486a6ca5cc941597d34c4b31/mimium-midi/src/lib.rs#L140

**Comment by tomoyanonymous** [comment]
Does the panic happens on realtime audio? I guess the LocalBufferDriver somehow triggers `after_main` more than once.

**Comment by tomoyanonymous** [comment]
https://github.com/tomoyanonymous/mimium-rs/blob/00a43378674b567a486a6ca5cc941597d34c4b31/mimium-audiodriver/src/backends/local_buffer.rs#L91 

This part was no longer needed.

BTW, in the current implementation, the GUI launches after emitting csv. GUI tools plugin should be turned off if the command line option is non-realtime context.

**Comment by yutannihilation** [comment]
> Does the panic happens on realtime audio?

No, it works fine.

**Comment by yutannihilation** [comment]
> This part was no longer needed.

Oh, it seems removing this line fixes the panic, thanks.
